spring.datasource.url=jdbc:postgresql://dpg-d77dfb5m5p6s73ae4n4g-a:5432/auto_weld
spring.datasource.username=auto
spring.datasource.password=XkgniVXShh0DokQc0vTClrM9Ix0oUO6c

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}